language: minimal

before_deploy:
  - docker build -t janniswarnat/helloworld-express-app:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: script
    script: docker push janniswarnat/helloworld-express-app:latest
    on:
      branch: master
